future: true
permalink: /:title/
url: http://sternigths.github.io
name: sternights
author: 黄伟浩
qq: 405520368
email: waihowong02@gmail.com

duoshuo: 
beian: 
cnzz: 
weibo: 
github: STERNIGTHS
about: "创建于 2018 年。"

safe: true
paginate: 20
